---
- hosts: loadbalancer
  become: true
  gather_facts: false
  tasks:
    - name: status of nginx
      command: service nginx status
      changed_when: false

    - name: verify if nginx listening on port 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  gather_facts: false
  tasks:
    - name: status of apache
      command: service apache2 status
      changed_when: false

    - name: verify if apache2 listening on port 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: status of mysql
      command: service mysql status
      changed_when: false

    - name: verify if mysql listening on port 3306
      wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 timeout=1

- hosts: control
  gather_facts: false
  tasks:
    - name: verify end to end response
      #uri: url=http://{{item}} return_content=yes
      uri: url=http://lb01 return_content=yes
      #with_items: groups.loadbalancer
      register: lb_index

      #- debug: var=lb_index.content

    - fail: msg="index failed to return content"
      when: lb_index.status != 200
      #when: "'Hello, from sunny' not in item.content" 
      #with_items: "{{lb_index.results}}"

- hosts: loadbalancer
  tasks:
    - name: verify backend response
      uri: url=http://{{item}} return_content=yes
      with_items: "{{groups.webserver}}"
      register: app_index

    - fail: msg="index failed to return content"
      when: "'Hello, from sunny {{item.item}}!' not in item.content" 
      with_items: "{{app_index.results}}"
