---
# tasks file for control
- name: install tools
  apt: name={{item}} state=present
  with_items:
    - curl
    - python-httplib2
    - tree
    - python-boto
    - python-pip
  tags: ['packages']
