---
# tasks file for apache2
- name: install web components
  apt: name={{item}} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi
  tags: [ 'packages' ]

- name: ensure additional module is enabled
  apache2_module: state=present name=wsgi
  notify: restart apache handler
  tags: [ 'configure' ]

- name: deactivate default site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache handler
  tags: [ 'configure' ]

- name: ensure apache2 is started
  service: name=apache2 state=started enabled=yes
  tags: [ 'service' ]
